apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: cita-bot
build:
  artifacts:
  - image: cdutten/cita-bot-test
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/cita-bot-deploy.yaml
    - k8s/cita-bot-ns.yaml
